version: "3.8"
services:
    postgres:
        container_name: postgres
        image: "postgres:alpine"
        env_file: .env
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_DB: ${POSTGRES_DATABASE}
        ports:
            - "5432:5432"
        volumes:
            - ./.dbdata:/var/lib/postgresql/data:rw
        networks:
            - backend

    users-api:
        container_name: users-api
        build:
            context: .
            target: dev
        image: users-api
        ports:
            - "8080:8080"
            - "2345:2345"
        env_file: .env
        depends_on:
            - postgres
        volumes:
            - .:/usr/src/users-api:rw,delegated
        networks:
            - backend
        command: ["./docker/entrypoint.sh", "postgres:5432", "air"]

networks:
    backend:
        driver: "bridge"
